#!/usr/bin/env python3
"""Audit report and optional GitHub issue creation for integrity checks.

Imports integrity-check.py, runs all checks, writes data/audit-report.json.
Creates GitHub issues for failed checks when --create-issues is passed.

No secrets.  Only stdlib + psycopg3.  Uses `gh` CLI for issue operations.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# integrity-check.py has a hyphen; use importlib to load it.
_ic_path = Path(__file__).resolve().parent / "integrity-check.py"
_ic_spec = importlib.util.spec_from_file_location("integrity_check", _ic_path)
ic = importlib.util.module_from_spec(_ic_spec)
_ic_spec.loader.exec_module(ic)


AUDIT_REPORT = Path(__file__).resolve().parents[2] / "data" / "audit-report.json"
ISSUE_LABELS = ["data-integrity", "completeness", "schema-violation"]


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def build_report(results: list[dict]) -> dict:
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "checks": [
            {
                "name": r["name"],
                "status": r.get("status", "ERROR"),
                "details": r.get("detail", ""),
            }
            for r in results
        ],
    }


def write_report(report: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Audit report written to {path}")


# ---------------------------------------------------------------------------
# GitHub issues
# ---------------------------------------------------------------------------

def existing_issue_titles(repo: str) -> set[str]:
    """Return a set of all open issue title substrings for the repo.

    Lets errors propagate: a missing gh binary or bad repo name must not
    silently break idempotency.
    """
    out = subprocess.check_output(
        ["gh", "issue", "list", "--repo", repo, "--state", "open",
         "--limit", "200", "--json", "title"],
        text=True,
        stderr=subprocess.DEVNULL,
    )
    issues = json.loads(out)
    return {i["title"] for i in issues}


def create_issues(report: dict, repo: str, dry_run: bool) -> int:
    """Create GitHub issues for failed checks. Returns count of issues created/skipped."""
    titles = existing_issue_titles(repo)
    created = 0

    for check in report["checks"]:
        if check["status"] not in ("FAIL", "ERROR"):
            continue

        title = f"Integrity check failed: {check['name']}"
        if title in titles:
            print(f"  SKIP (already exists): {title}")
            continue

        body = (
            f"## Integrity Check Failure\n\n"
            f"**Check:** `{check['name']}`\n"
            f"**Status:** {check['status']}\n"
            f"**Details:**\n\n```\n{check['details']}\n```\n\n"
            f"---\n*Generated by audit-create-issues.py at {report['generated_at']}*"
        )

        if dry_run:
            print(f"  DRY-RUN would create: {title}")
        else:
            subprocess.run(
                ["gh", "issue", "create", "--repo", repo,
                 "--title", title, "--body", body,
                 "--label", ",".join(ISSUE_LABELS)],
                check=True,
            )
            print(f"  CREATED: {title}")
            created += 1

    return created


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run integrity checks, write audit report, optionally create GitHub issues.",
    )
    parser.add_argument(
        "--database-url",
        help="PostgreSQL connection URL (overrides $DB_URL env var)",
    )
    parser.add_argument(
        "--report-path",
        type=Path,
        default=AUDIT_REPORT,
        help=f"Path for audit report JSON (default: {AUDIT_REPORT})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Report only, do not create issues (this is the default behaviour)",
    )
    parser.add_argument(
        "--create-issues",
        action="store_true",
        help="Create GitHub issues for failed checks (requires --repo)",
    )
    parser.add_argument(
        "--repo",
        help="GitHub OWNER/REPO for issue creation (required with --create-issues)",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    # --repo validation
    if args.create_issues and not args.repo:
        parser.error("--repo OWNER/REPO is required when --create-issues is set")

    # Connect and run checks
    url = ic._get_db_url(args)
    conn = ic._connect(url)
    try:
        results = ic.run_all_checks(conn)
    finally:
        conn.close()

    # Build and write report
    report = build_report(results)
    write_report(report, args.report_path)

    # Determine exit code
    failed = [r for r in results if r.get("status") in ("FAIL", "ERROR")]
    exit_code = 1 if failed else 0

    # Issue creation: --create-issues means "actually create" regardless of --dry-run
    if args.create_issues:
        count = create_issues(report, args.repo, dry_run=False)
        print(f"Issues created: {count}")

    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
