repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/sbdchd/squawk
    rev: v2.64.0
    hooks:
      - id: squawk
        files: src/db/migrations-pg/*.sql
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.3.0
    hooks:
      - id: sqlfluff-lint